version: "3.2"

services:
  substrate:
    container_name: substrate
    image: projetsim/substrate-sim:latest
    ports:
      - "9944:9944"
    expose: 
      - "9615"
    volumes:
      - ./node-data:/root/.local
    # command: bash -c "cargo build --release && RUST_LOG=runtime=debug ./target/release/node-template --dev --ws-external --prometheus-external"
    command: bash -c "RUST_LOG=runtime=debug node-template --dev --ws-external --prometheus-external"

  substrate-rest-api:
    image: docker.io/parity/substrate-api-sidecar:latest
    container_name: substrate-rest-api
    ports:
      - 8888:8888
    environment:
      - SAS_EXPRESS_PORT=8888
      - SAS_SUBSTRATE_WS_URL=ws://substrate:9944

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data:/prometheus
    user: "root"
    expose: 
      - "9090"
    depends_on:
      - substrate

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    expose: 
      - "9090"
      - "9615"
    volumes:
      - ./grafana-data:/var/lib/grafana
    user: "472" #don't forget to do a chown
    depends_on:
      - substrate
      - prometheus

  # substrate-interface:
  #   build:
  #       context: ./substrate-SIM-frontend
  #       dockerfile: Dockerfile
  #   container_name: substrate-interface
  #   working_dir: /var/www/node-template-frontend
  #   ports:
  #     - 8000:8000
  #   expose: 
  #     - "9090"
  #     - "9944"
  #     - "9615"
  #   volumes:
  #     - ./substrate-SIM-frontend:/var/www/node-template-frontend
  #   depends_on:
  #     - substrate
  #   environment:
  #     - BROWSER=none
  #   command: bash -c "yarn install && yarn start"
