{
 "title": "Substrate Node Template Metrics",
 "description": "Grafana dashboard for substrate template metrics. Instructions on use: https://substrate.dev/docs/en/tutorials/visualize-node-metrics/",
 "tags": [
  "substrate",
  "blockchain",
  "node",
  "template",
  "polkadot",
  "kusama"
 ],
 "time": { "from": "2021-05-07T09:33:38.065Z", "to": "2021-05-07T09:37:39.439Z" },
 "panels": [
  { "title": "Node/chain data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height (best)",
   "type": "graph",
   "description": "What your node sees as the highest block (NOT finalized)",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_block_height{status=\"best\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block Height (finalized)",
   "type": "graph",
   "description": "What your node sees as the highest finalized block ( less than or equal to best)",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_block_height{status=\"finalized\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total submitted tx ",
   "type": "graph",
   "description": "Total transactions that were submitted for validation",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_txpool_submitted_transactions",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total finished tx ",
   "type": "graph",
   "description": "Total transactions that finished validation",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_txpool_validations_finished",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total finished tx rate",
   "type": "gauge",
   "description": "Total transactions that finished validation",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(substrate_sub_txpool_validations_finished[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total finished tx rate",
   "type": "graph",
   "description": "Total transactions that finished validation",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_sub_txpool_validations_finished[$__interval])",
     "legendFormat": "{{job}} rate"
    }
   ]
  },
  {
   "title": "Ready Queue size",
   "type": "graph",
   "description": "Ready Queue - Contains transactions that can be included in a new pending block. For runtimes built with FRAME, the transactions must follow the exact order in the ready queue.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "substrate_ready_transactions_number",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Tx invalid",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_txpool_validations_invalid",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "P2P/communication information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC calls",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(substrate_rpc_calls_total[5m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "P2P requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(substrate_sub_libp2p_requests_out_success_total_sum)",
       "legendFormat": "sum out request count"
      },
      {
       "expr": "sum(substrate_sub_libp2p_requests_in_success_total_sum)",
       "legendFormat": "sum in request count"
      }
     ]
    },
    {
     "title": "Proposer Block Construction Time",
     "type": "graph",
     "description": "histogram 90th quantiles for time to construct a block (seconds) More info: https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "Time (s)" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(substrate_proposer_block_constructed_bucket[5m])) by (le))",
       "legendFormat": "90th quantile for block construction time (s)"
      }
     ]
    },
    {
     "title": "State Cashe (bytes)",
     "type": "graph",
     "description": "What your node sees as the highest finalized block ( less than or equal to best)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "substrate_state_cache_bytes", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "LibP2P peers",
     "type": "bargauge",
     "description": "Number of connected peers",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "substrate_sub_libp2p_peers_count",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  }
 ]
}