IMAGE_NAME = "bento/ubuntu-20.04"
K8S_NAME = "sim-cluster"
MASTERS_NUM = 1
MASTERS_CPU = 2 
MASTERS_MEM = 2048
MASTER_NAME="master"

NODES_NUM = 2
NODES_CPU = 2
NODES_MEM = 2048

IP_BASE = "192.168.50."

VAGRANT_DISABLE_VBOXSYMLINKCREATE=1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
     
        config.vm.define MASTER_NAME do |master|
            master.vm.box = IMAGE_NAME
            master.vm.network "private_network", ip: "#{IP_BASE}10"
            master.vm.hostname = MASTER_NAME
            master.vm.provider "virtualbox" do |v|
                v.memory = MASTERS_MEM
                v.cpus = MASTERS_CPU
                v.name = MASTER_NAME
                #v.gui = true
            end            
            master.vm.provision "ansible" do |ansible|
                ansible.playbook = "roles/k8s.yml"
                #Redefine defaults
                ansible.extra_vars = {
                    k8s_cluster_name:       K8S_NAME,                    
                    k8s_master_admin_user:  "vagrant",
                    k8s_master_admin_group: "vagrant",
                    k8s_master_apiserver_advertise_address: "#{IP_BASE}10",
                    k8s_master_node_name: MASTER_NAME,
                    k8s_node_public_ip: "#{IP_BASE}10"
                }                
            end
        end


    (1..NODES_NUM).each do |j|
        config.vm.define "worker-#{j}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "#{IP_BASE}#{j + 10}"
            node.vm.hostname = "worker-#{j}"
            node.vm.provider "virtualbox" do |v|
                v.memory = NODES_MEM
                v.cpus = NODES_CPU
                v.name = "worker-#{j}"
                #v.customize ["modifyvm", :id, "--cpuexecutioncap", "20"]
                #v.gui = true
            end             
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "roles/k8s.yml"                   
                #Redefine defaults
                ansible.extra_vars = {
                    k8s_cluster_name:     K8S_NAME,
                    k8s_node_admin_user:  "vagrant",
                    k8s_node_admin_group: "vagrant",
                    k8s_node_public_ip: "#{IP_BASE}#{j + 10}"
                }
            end
        end
    end
end
