# The host and port for Open TSDB database used for metrics
opentsdb_url = "http://influxdb:8086"

# The name of the database used for storing metrics
opentsdb_db = "metrics"

opentsdb_username  = "admin"

opentsdb_password  = "admin"
